name: Build Mesen

on:
  push:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  windows:
    strategy:
      matrix:
        os: [windows-latest]
        netversion: [6.x,_8.x]
        targetframework: [net6.0,_net8.0]
        aot: [false,_true]
        singleFile: [true,_false]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.netversion }}

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Restore packages
        run: dotnet restore -p:TargetFramework="${{ matrix.targetframework }}" -r win-x64 -p:PublishAot="${{ matrix.aot }}"

      - name: Build Mesen
        run: msbuild -nologo -v:d -clp:ForceConsoleColor -m -p:Configuration=Release -p:Platform=x64 -t:Clean,UI -p:TargetFramework="${{ matrix.targetframework }}"

      - name: Publish Mesen
        run: dotnet publish --no-restore -c Release -p:PublishAot="${{ matrix.aot }}" -p:SelfContained="${{ matrix.aot }}" -p:PublishSingleFile="${{ matrix.singleFile }}" -p:OptimizeUi="true" -p:Platform="Any CPU" -p:TargetFramework="${{ matrix.targetframework }}" -r win-x64 Mesen.sln /p:PublishProfile=UI\Properties\PublishProfiles\Release.pubxml

      - name: Upload Mesen
        uses: actions/upload-artifact@v4
        with:
          name: Mesen (Windows - ${{ matrix.targetframework }}${{ matrix.aot ? ' - AoT' : '' }})
          path: build/TmpReleaseBuild/Mesen.exe

  linux:
    strategy:
      matrix:
        os: [ubuntu-22.04,_ubuntu-20.04]
        compiler: [gcc,_clang,_clang_aot]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        run: |
          sudo apt-get update -qy
          sudo apt-get install -qy libsdl2-dev

      - name: Build Mesen
        run: |
          make -j$(nproc) USE_GCC=${compiler == 'gcc'} USE_AOT=${compiler == 'clang_aot'} LTO=true STATICLINK=true SYSTEM_LIBEVDEV=false

      - name: Upload Mesen
        uses: actions/upload-artifact@v4
        with:
          name: Mesen (Linux - ${{ matrix.os }} - ${{ matrix.compiler }})
          path: bin/linux-x64/Release/linux-x64/publish/Mesen

  appimage:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        run: |
          sudo apt-get update -qy
          sudo apt-get install -qy libsdl2-dev libfuse2

      - name: Build Mesen (AppImage)
        run: |
          Linux/appimage/appimage.sh

      - name: Upload Mesen (AppImage)
        uses: actions/upload-artifact@v4
        with:
          name: Mesen (Linux x64 - AppImage)
          path: Mesen.AppImage

  macos:
    strategy:
      matrix:
        os: [macos-12,_macos-14]
        arch: [x64,_arm64]
        compiler: [clang,_clang_aot]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        run: |
          brew install sdl2

      - name: Build Mesen
        run: |
          make -j$(sysctl -n hw.logicalcpu) USE_AOT=${compiler == 'clang_aot'}

      - name: Sign binary
        env:
          APP_NAME: bin/osx-${{ matrix.arch }}/Release/osx-${{ matrix.arch }}/publish/Mesen.app
          CERT_DATA: ${{ secrets.MACOS_CERTIFICATE }}
          CERT_PASS: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          ENTITLEMENTS: UI/Mesen.entitlements
          SIGNING_IDENTITY: Mesen
        run: |
          # Export certs
          echo "$CERT_DATA" | base64 --decode > /tmp/certs.p12
          # Create keychain
          security create-keychain -p actions macos-build.keychain
          security default-keychain -s macos-build.keychain
          security unlock-keychain -p actions macos-build.keychain
          security set-keychain-settings -t 3600 -u macos-build.keychain
          # Import certs to keychain
          security import /tmp/certs.p12 -k ~/Library/Keychains/macos-build.keychain -P "$CERT_PASS" -T /usr/bin/codesign -T /usr/bin/productsign
          # Key signing
          security set-key-partition-list -S apple-tool:,apple: -s -k actions macos-build.keychain
          # print identities
          security find-identity -v macos-build.keychain

          echo "[INFO] Signing app file"
          codesign --force --deep --timestamp --keychain macos-build.keychain --options=runtime --entitlements "$ENTITLEMENTS" --sign "$SIGNING_IDENTITY" "$APP_NAME"

      - name: Zip Mesen.app
        run: |
          ditto -c -k --sequesterRsrc --keepParent bin/osx-${{ matrix.arch }}/Release/osx-${{ matrix.arch }}/publish/Mesen.app bin/osx-${{ matrix.arch }}/Release/Mesen.app.zip

      - name: Upload Mesen
        uses: actions/upload-artifact@v4
        with:
          name: Mesen (macOS - ${{ matrix.os }} - ${{ matrix.compiler }})
          path: bin/osx-${{ matrix.arch }}/Release/Mesen.app.zip
